### PR TITLE
PR to fix issue #42—clarifying meaning of a sentence in intro

### LINKED ISSUE #42: [Introduction] Clarify...
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/218)

### PR DESCRIPTION
**Pull request by talltree**
Fixes #42 

Added sentence to clarify question of meaning that was raised in the issue.

Signed-off-by: Drummond Reed <drummond@connect.me>

***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-spec/pull/79.html" title="Last updated on Oct 17, 2019, 10:12 PM UTC (fe239b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-spec/79/f41a80d...talltree:fe239b0.html" title="Last updated on Oct 17, 2019, 10:12 PM UTC (fe239b0)">Diff</a>

### CODE REVIEW

**Comment by talltree** [comment]
@iherman I tried to link my W3C account to my github account but it gave an error. Note that my github account uses a different email than my W3C account. What should I do next?

**Comment by peacekeeper** [comment]
Great first PR, congrats @talltree :)

**Comment by iherman** [comment]
@talltree I have copied you on a mail I sent to our system people.

**Comment by peacekeeper** [comment]
Wording in this PR originally proposed by @rhiaro - see https://github.com/w3c-ccg/did-spec/issues/218#issuecomment-519609186

**Comment by msporny** [comment]
Editorial, @talltree is clearly in the group (ignoring IPR warning), multiple positive reviews. Merging.

**Pull request merged**
